"vimrc - VIM Configuration file"

"Autointend and autoscroll 3 lines above the cursor"
:set cindent
:set scrolloff=3

"Tabstop, Shiftwith and replace tabs with spaces but not in makefiles 
:set tabstop=4
:set shiftwidth=4
:set expandtab
:autocmd FileType make set noexpandtab

"Stuff needed by urxvt"
:set nocompatible
:set mouse=a
:set backspace=2

"Syntaxhighlighting, colorscheme, linenumbers"
:syntax on
:set background=dark
:colorscheme lettuce
:set t_Co=256
:set number
:set list
:set nowrap
:set hlsearch

"Automaticly reread a file, if file has changed"
set autoread
